export const SELECTORS = {
    autoModalLoginBtn: 'button[id="id-auto-modal"]',
    emailField: 'input[placeholder="john@example.com"]',
    passwordField: 'input[type="password"]',
    defaultBtn: '.el-button.el-button--default',
    primaryBtn: 'button.el-button--primary',
    saveBtn: 'button.el-button--warning',
    warnBtn: 'button.el-button--warning',
    toggleBtn: '.el-switch',
    errorAlert: '.el-alert.el-alert--error',
    warnAlert: '.el-alert.el-alert--warning',
    errorInputField: '.el-form-item__error',
    modalDialog: '.el-overlay',
    messageBox: '.el-message-box',
    formElement: '.form-element',
    formBase: '.el-collapse .el-collapse-item:first-child button',
    formAdvance: '.el-collapse .el-collapse-item:nth-child(2) button',
    formPayment: '.el-collapse .el-collapse-item:nth-child(3) button',
    formUserDefine: '.el-collapse .el-collapse-item:last-child button',
    formTitle: '.el-input__inner',
    formDescription: '.el-textarea__inner',
    dropdown: '.el-dropdown',
    dropdownMenu: 'ul.el-dropdown-menu',
};